version: '3.4'
services:
  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./custom_pipeline:/app/custom_pipeline
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug -p 5006"
    ports:
    - '5006:5005'
    public: true
    networks:
    - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./custom_pipeline:/app/custom_pipeline
    command: ["rasa", "run", "actions"]
    ports:
    - '5056:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"