version: '3.4'
services:
  food-lover-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./custom_pipeline:/app/custom_pipeline
    - ./models:/app/models
    command: bash -c "rasa run -m models --enable-api --cors \"*\" --debug"
    ports:
    - '5006:5005'
    public: true
    networks:
    - all

  food-lover-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./custom_pipeline:/app/custom_pipeline
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    public: true
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"