INGREDIENT_TYPE = {
    "3": ["Cá "],
    "213": ["Tôm tươi"],
    "57": ["Tôm"],
    "58": ["Cua"],
    "59": ["Ghẹ "],
    "56": ["Mực", "Bạch tuộc"],
    "63": ["Ốc"],
    "64": ["Sò"],
    "65": ["Hàu"],
    "84": ["Bào ngư"],
    "187": ["Loại thủy hải sản khác"],
    "194": ["Chuột "],
    "2": ["Heo"],
    "18": ["Bò"],
    "212": ["Thịt nạc vai"],
    "5": ["Gà"],
    "8": ["Vịt"],
    "22": ["Dê"],
    "36": ["Ếch"],
    "24": ["Chim"],
    "30": ["Thỏ"],
    "25": ["Cầy"],
    "53": ["Mèo"],
    "61": ["Cừu"],
    "15": ["Bò Sát"],
    "106": ["Trâu"],
    "107": ["Nai"],
    "141": ["Ngỗng"],
    "142": ["Ngan (Vịt xiêm)"],
    "120": ["Rau"],
    "121": ["Củ "],
    "144": ["Quả"],
    "191": ["Loại bột khác"],
    "119": ["Tinh bột"],
    "23": ["Ngũ cốc"],
    "185": ["Dầu", "Bơ", "Phomai"],
    "192": ["Bánh", "Kem", "Chocolate"],
    "193": ["Trà", "Chè", "Thạch"],
    "211": ["Gia vị nấu phở"],
    "131": ["Bún", "Mì", "Nui"],
    "9": ["Trái cây"],
    "31": ["Đồ chay"],
    "20": ["Nấm"],
    "28": ["Côn trùng"],
    "6": ["Trứng"],
    "13": ["Đậu hũ"],
    "37": ["Chả", "Giò", "Thịt nguội"],
    "16": ["Dược liệu", "Cây thuốc"],
    "17": ["Thức uống"],
    "188": ["Đường", "Mật ong"],
    "10": ["Gia Vị"],
    "26": ["Mứt"],
    "27": ["Hạt"],
    "32": ["Sữa"]
}

DISH_TYPE = {
    "104": ["Salad"],
    "105": ["Nước chấm", "Sốt"],
    "106": ["Canh"],
    "107": ["Lẩu "],
    "108": ["Nộm", "Gỏi"],
    "109": ["Soup", "Cháo"],
    "110": ["Nem", "Chả"],
    "111": ["Chay"],
    "112": ["Xôi"],
    "113": ["Bánh mặn"],
    "114": ["Bánh ngọt"],
    "115": ["Sinh tố", "Nước ép"],
    "117": ["Cocktail", "Mocktail"],
    "118": ["Kem"],
    "119": ["Chè "],
    "120": ["Mứt", "Kẹo"],
    "121": ["Đồ sống"],
    "122": ["Snacks"],
    "123": ["Cupcake", "Muffin"],
    "124": ["Pasta", "Spaghetti"],
    "125": ["Miến", "Hủ tiếu"],
    "126": ["Bún", "Mì", "Phở"],
    "127": ["Đồ uống"],
    "128": ["Nướng", "Quay"],
    "129": ["Nghêu", "Sò", "Ốc"],
    "130": ["Rang", "Xào"],
    "131": ["Món chiên"],
    "132": ["Món cuốn"],
    "133": ["Chưng", "hấp"],
    "135": ["Muối chua", "Ngâm chua"],
    "136": ["Kho", "Rim"],
    "137": ["Ủ", "Lên men"],
    "138": ["Món luộc"],
    "139": ["Thạch", "Rau câu"],
    "140": ["Sữa chua"]
}

CUISINES = {
    "1": ["Món Việt"],
    "2": ["Món Thái"],
    "4": ["Món Hàn"],
    "5": ["Món Nhật"],
    "6": ["Món Âu"],
    "7": ["Món Hoa"],
    "8": ["Món Ấn"],
    "9": ["Món Sing"],
    "11": ["Món Latin"],
    "12": ["Món Âu"],
    "17": ["Món Indonesia"],
    "18": ["Món Nga"],
    "19": ["Món Malaysia"],
    "20": ["Món Philippines"]
}

LEVELS = {
    "1": ["Dễ"],
    "2": ["Trung bình"],
    "3": ["Khó"]
}

PURPOSES = {
    "5": ["Giảm cân", "Ăn kiêng"],
    "6": ["Cho phái mạnh"],
    "9": ["Ăn chay"],
    "12": ["Phụ nữ sau khi sinh"],
    "13": ["Phụ nữ mang thai"],
    "14": ["Trẻ dưới 1 tuổi"],
    "15": ["Cho sức khỏe"],
    "17": ["Cho trẻ em"],
    "18": ["Cho tim mạch"],
    "19": ["Cho phái nữ"],
    "21": ["Tăng cân"]
}

COOKING_METHOD = {
    "33": ["Luộc", "Hấp"],
    "34": ["Chiên", "Xào", "Xốt", "Rang"],
    "35": ["Hầm", "Om", "Kho", "Ram"],
    "36": ["Quay", "Nướng"],
    "37": ["Ngâm", "Ủ", "Muối"],
    "38": ["Ép", "Vắt", "Xay"],
    "39": ["Trộn", "Cuốn"]
}

OCCAIONS = {
    "1": ["Giáng sinh"],
    "2": ["Tết"],
    "3": ["Sinh nhật"],
    "4": ["Lễ tình nhân"],
    "5": ["Ngày phụ nữ"],
    "7": ["Cơm gia đình"],
    "8": ["Lễ hỏi", "Lễ cưới"],
    "9": ["Ngày ăn chay"],
    "10": ["Ngày thường"],
    "11": ["Trung thu"],
    "12": ["Halloween"]
}
